### ISSUE TITLE
Local dev environment Sentry reporting

### ISSUE THREAD

**Issue by CharlesCarnell** [kentcc/kentgov#17]
https://app.getsentry.com/kent-county-council/kentgov/issues/108880663/

```
TypeError: Cannot read property 'top' of undefined
  at Object.kcc.tabs.scrollToTopOfTabHeading (/assets/js/custom.js:310:86)
  at Object.kcc.tabs.changeTab (/assets/js/custom.js:318:9)
  at Object.kcc.tabs.handleHashChange (/assets/js/custom.js:298:10)
  at n.event.dispatch (/assets/js/vendor.js:7:12344)
  at r.handle (/assets/js/vendor.js:7:9071)
```

**Comment by CharlesCarnell** [comment]
Resolved in e987d03f8d8e37ac21f03932e3bde78f902eead8
